### ISSUE TITLE
Throws error in electron

### ISSUE THREAD

**Issue by ThatOneCalculator** [juliangruber/offline#3]
Not sure if you'll see this given the project's age, but it's worth a shot.

When I run this in my electron project, I get

```
(node:244937) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined
    at module.exports (/home/kainoa/Documents/DRPCM/gui/node_modules/offline/index.js:8:3)
    at createWindow (/home/kainoa/Documents/DRPCM/gui/main.js:51:7)
(node:244937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:244937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by juliangruber** [comment]
Hey, I assume you run this in the Server context, there it will fail, but it will work in the Browser context. There might be better alternatives nowadays however
